### ISSUE TITLE
know when stores hydrated

### ISSUE THREAD

**Issue by barbarosso** [pinqy520/mobx-persist#27]
Hello,
First, i would like to tell you, the mobx-persist library rocks :-)
I have following case, where i have a store that has a persisted list.
i also have a reaction that listens to changes of the lengt of the array.
Everything works as expected, except when i reload the page, the reaction also triggers the reaction. Is there a way to detect if the store has been hydrated or not?

Regards
Pascal

```js
export default class TestStore {
  @persist("list")
  @observable
  tests = [];

constructor() {

    reaction(
      () => this.tests.length,
      length => {
        if (length > 0) {
          console.log('the array is empty')
        } else {
          console.log('the array has items')
        }
      }
    );
```

**Comment by barbarosso** [comment]
@pinqy520 That did indeed solve my problem, but i was hoping on a more elegant solution.
Now i have to create an extra function to enable my reactions, and call those when the hydration Finished.

**Comment by pinqy520** [comment]
Hi, you don't need to create an extra function.

**Comment by matdehaast** [comment]
@pinqy520 so if I instantiate the a new store in the argument of hydrate will the constructor of that store only be called after the data is already hydrated in the store?

Or is it better to have an initialisation function within the store that would otherwise do constructor stuff and call that after the hydration has completed?
