### ISSUE TITLE
Add support?! to mobx-state-tree

### ISSUE THREAD

**Issue by yordis** [pinqy520/mobx-persist#37]
Any idea how can we use this with mobx-state-tree?

**Comment by pinqy520** [comment]
#33

**Comment by yordis** [comment]
@pinqy520 I think is worth to add that example to the readme, it will help a lot people.

But also the point of my request this is to have the same API, where you can setup the storage you want and the fields of the data structure you want to save by default. Just look how many checks like one https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mst-example-bookshop/src/stores/CartStore.js#L56 is happening. The proposal is to use a common package for this interaction.

**Comment by pinqy520** [comment]
I think I understand your request now, and I will try to support MST when I have time. My job is quite busy, recently.

**Comment by yordis** [comment]
@pinqy520 hey man, are you gonna consider to open this issue?

**Comment by nickbreaton** [comment]
If it is decided to make this a separate package, I grabbed the npm name `mst-persist` a while back, but never did anything with it. Ping me if you want to publish under that name and I'll hand it over.

**Comment by CodyBrouwers** [comment]
Found this gist that I might try using:
https://gist.github.com/benjick/c48dd2db575e79c7b0b1043de4556ebc

Otherwise, I too would be interested in direct mobx state tree support from this library.

**Comment by tallpants** [comment]
If anyone's interested, I have a super simple working example repo that includes a helper to initialize the store and configure it for persistence, a way to pass in a default state snapshot for when no persisted state is found, an `injectStore` HOC, and a `<PersistGate />` component similar to Redux Persist that delays rendering until the store is initialized: https://github.com/tallpants/mobx-state-tree-persist-example

It's web only, but you can adapt it for React Native by changing `storage.js` to use `AsyncStorage` instead of `localforage`.

**Comment by AdamGerthel** [comment]
I haven't used MST, but it looks like you don't really need more than a few lines of code to do this without mobx-persist since MST already handles all the serialization/deserialization. In the egghead video by the MobX creator (Michel Weststrate), it looks extremely straightforward:
https://egghead.io/lessons/react-store-store-in-local-storage

**Comment by agilgur5** [comment]
Hey folks, since there were a bunch of examples here, but no concrete library, I decided to make my own at [agilgur5/mst-persist](https://github.com/agilgur5/mst-persist). It takes as inspiration some of the examples here, as well as mobx-persist and redux-persist.

I extracted it out of an [RN app of mine](https://github.com/agilgur5/react-native-manga-reader-app) and it's currently being used in it in production there. It supports whitelists and blacklists out-of-the-box and I'm planning on adding transforms to support some of my own use cases as well.

@nickbreaton would appreciate if you could transfer ownership of the NPM package to me so I can publish it under the same name! :)

Since the dependencies are different between `mobx-persist` (MobX and `serializr`) and `mst-persist` (just MST), I didn't think a PR made sense. That being said, a bunch of the components of `mobx-persist`, `redux-persist`, and `mst-persist` are very similar (with minor differences/features). I didn't want to introduce dependencies to either (though `redux-persist` is good at splitting up different parts from each other, would still have to install unnecessary things), but it would be good to have some "core" library that could be used by different persistence libs, handling common things like storage adaptors, persist gates, etc.

**Comment by nickbreaton** [comment]
@agilgur5 You should be good to go! 👍

**Comment by agilgur5** [comment]
Thanks @nickbreaton ! Just published [v0.0.1](https://www.npmjs.com/package/mst-persist)!

@pinqy520 or @yordis think we can close this one out now. hope to collaborate more in the future on similar features :)

**Comment by yordis** [comment]
@agilgur5 Amazing!
